### ISSUE TITLE
Add author selection?

### ISSUE THREAD

**Issue by KarateKugler** [iamdangry/silverbullet-dailyquote#1]
I love this! Been getting into silverbullet the last week and some daily quotes are such a great idea for the daily work flow. Though if you take all advice it just cancels out to zero (quote by Naval hehe) so if theres a way to narrow down by authors instead of tags, that would be neatttt.

**Comment by iamdangry** [comment]
That's great to hear! Glad you've adopted it into your flow.

Absolutely I can add support for filtering by author.

**Comment by iamdangry** [comment]
Added to [0.2.0](https://github.com/iamdangry/silverbullet-dailyquote/releases/tag/0.2.0)

Can now include or exclude author/s. Below is just an example. Obviously only a single author belongs to each quote, so combing the includeAuthors and excludeAuthors setting will do nothing.

```
DailyQuote:
  includeTags: ["Wisdom", "Success", "Famous Quotes"]
  excludeTags: ["Change", "Life"]
  includeAuthors: ["Confucius", "Winston Churchill"]
  excludeAuthors: ["Anatole France"]
```
